#!/bin/sh

# TODO: gather version number from input.
VERSION=1.9.15
BASEDIR=$PWD

SRCDIR=$BASEDIR/nginx-$VERSION

echo "Getting Nginx source version" $VERSION
cd $SRCDIR
if [ ! -f nginx-$VERSION.tar.gz ]; then
    wget nginx.org/download/nginx-$VERSION.tar.gz
fi
tar zxf nginx-$VERSION.tar.gz
